-- 프로그래머스: 오프라인/온라인 판매 데이터 통합하기
-- union, 없는 컬럼 null로 출력하기 모르는 부분 검색 후 풀이했음

-- 온라인 상품 판매 정보 테이블 = ONLINE_SALE
-- 오프라인 상품 판매 정보 테이블 = OFFLINE_SALE
-- 온라인의 SALES_DATE, USER_ID, PRODUCT_ID 조합은 하나만 존재
-- 오프라인의 SALES_DATE, PRODUCT_ID 조합은 하나만 존재
-- 2022년 3월 오프/온라인의 SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT 출력
-- OFFLINE_SALE의 USER_ID는 NULL로 표시
-- SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC

    SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
    FROM ONLINE_SALE
    WHERE SALES_DATE LIKE '2022-03%'
UNION
    SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
    FROM OFFLINE_SALE
    WHERE SALES_DATE LIKE '2022-03%'
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC;